package sheet9Inheritence;


	enum Colour{WHITE,RED,BLUE,YELLOW,ORANGE,GREEN,BROWN,BLACK};
	enum MaterialType{WOOD,CANE,PVC,STEEL,CHROME,GLASS,PLASTIC,ACRYLIC,LEATHER,NYLON};
	enum Size{SINGLE,TWIN,DOUBLE,QUEEN,KING,OLYMPIC_QUEEN,GRAND_KING};
	enum Type{OFFICE,KITCHEN,BREAKFEAST,LAZY};
	enum Shape{ROUND, SQUARE, TRIANGLE, RECTANGLE, POLYGON, ICOSAGAN};

